id: 53570d25c7914e8a9c2a6a84fc53c1c5
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_115-The_Display_of_the_Pure_Land_of_Sukhavati-v1
  language: en
  author: ''
  volume: {}
